// <auto-generated/>
using Dapper;
using Microsoft.AspNetCore.Components;
using System.Data;
using System.Data.Common;

namespace CruddyDemo.Components
{
    /// <summary>
    /// Base class for a simple CRUD in a blazor component.
    /// </summary>
    public partial class CruddyBase5<T> : ComponentBase
    {
        /// <summary>
        /// Name of database table to 'CRUD'.
        /// </summary>
        [Parameter]
        public required string TableName { get; set; }

        /// <summary>
        /// A database connection e.g an SqlConnection or MysqlConnection. 
        /// </summary>
        [Parameter]
        public required DbConnection DbConnection { get; set; }

        /// <summary>
        /// Whether to show technical information.
        /// </summary>
        [Parameter]
        public bool? ShowTechInfo { get; set; }


        /// <summary>
        /// The rows retrieved from the database table in <seealso cref="TableName"/>.
        /// </summary>
        protected IQueryable<T> Rows;

        /// <summary>
        /// Calls first base.OnInitializedAsync() then FillRowsAsync().
        /// </summary>
        protected override async Task OnInitializedAsync()
        {
            await base.OnInitializedAsync();
            await FillRowsAsync();
        }

        /// <summary>
        /// This method should be overridden in derived classes to fill
        /// the rows from the database table <seealso cref="TableName"/>.
        /// </summary>
        protected virtual async Task FillRowsAsync()
        {
            Rows = await GetTableRowsAsync<T>();
        }

        /// <summary>
        /// Gets rows from the database table in <seealso cref="TableName"/> and maps them to a list of <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T1"></typ1eparam>
        public async Task<IQueryable<T1>> GetTableRowsAsync<T1>()
        {
            return await GetTableRowsAsync<T1>(DbConnection, TableName, "*");
        }

        /// <summary>
        /// Gets rows from the database table in <seealso cref="TableName"/> and maps them to a list of <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="DbConnection">A database connection e.g an SqlConnection (for MS SQL Server)/param>
        /// <param name="tableName">The rows retrieved from this database table.</param>
        /// <param name="cols">The columns to retrieve.</param>
        static public async Task<IQueryable<T1>> GetTableRowsAsync<T1>(DbConnection DbConnection, string tableName, string cols = "*")
        {
            var sql = $"SELECT {cols} FROM dbo.{tableName}";
            IEnumerable<dynamic> dynRows = await DbConnection.QueryAsync(sql);
            return Helpers.DynamicHelper.MapDynRows<T1>(dynRows).AsQueryable();
        }

    }
}
