// <auto-generated/>
using Microsoft.AspNetCore.Components;
using System.Data.Common;
using Dapper;

namespace CruddyDemo.Components
{
    /// <summary>
    /// Base class for a simple CRUD in a blazor component.
    /// </summary>
    public partial class Cruddy3
    {
        /// <summary>
        /// Name of database table to 'CRUD'.
        /// </summary>
        [Parameter]
        public required string TableName { get; set; }

        /// <summary>
        /// A database connection e.g an SqlConnection (for MS SQL Server)
        /// </summary>
        [Parameter]
        public required DbConnection DbConnection { get; set; }

        /// <summary>
        /// Whether to show technical information.
        /// </summary>
        [Parameter]
        public bool? ShowTechInfo { get; set; }

        /// <summary>
        /// The rows retrieved from the database table in <seealso cref="TableName"/>.
        /// </summary>
        protected IQueryable<Models.Customer> rows;

        /// <summary>
        /// Gets rows from the database table in <seealso cref="TableName"/> and maps them to a list of <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="DbConnection">A database connection e.g an SqlConnection (for MS SQL Server)/param>
        /// <param name="tableName">The rows retrieved from this database table.</param>
        /// <param name="cols">The columns to retrieve.</param>
        /// <returns></returns>
        protected IQueryable<T> GetTableRows<T>(DbConnection DbConnection, string tableName, string cols = "*")
        {
            var sql = $"SELECT {cols} FROM dbo.{tableName}";
            IEnumerable<dynamic> dynRows = DbConnection.Query(sql);
            return Helpers.DynamicHelper.MapDynRows<T>(dynRows).AsQueryable();
        }

        public override async Task SetParametersAsync(ParameterView parameters)
        {
            await base.SetParametersAsync(parameters);

            string tableName;
            if (parameters.TryGetValue<string>(nameof(TableName), out var value))
            {
                if (value is not null)
                {
                    tableName = value.Trim();
                    rows = GetTableRows<Models.Customer>(DbConnection, tableName);
                }
            }
        }

    }
}
